isc.DataSource.create({
    ID:"QuartzScheduler",
    serverConstructor:"com.isomorphic.scheduler.QuartzScheduler",
    fields:[
        {
            canEdit:false,
            name:"name",
            type:"text"
        },
        {
            canEdit:false,
            name:"state",
            type:"intEnum",
            valueMap:{
                "0":"Shutdown",
                "1":"Standby",
                "2":"Started"
            }
        }
    ],
    operationBinding:[
        {
            operationId:"start",
            operationType:"custom"
        },
        {
            operationId:"shutdown",
            operationType:"custom"
        },
        {
            operationId:"standby",
            operationType:"custom"
        },
        {
            operationId:"doit",
            operationType:"custom",
            serverObject:{
                className:"com.isomorphic.scheduler.QuartzScheduler",
                methodName:"doit"
            }
        }
    ]
})
