isc.DataSource.create({
    ID:"QuartzJobs",
    serverConstructor:"com.isomorphic.scheduler.QuartzJobs",
    fields:[
        {
            name:"group",
            primaryKey:true,
            required:true,
            type:"string"
        },
        {
            name:"name",
            primaryKey:true,
            required:true,
            type:"string"
        },
        {
            name:"description",
            type:"string"
        },
        {
            name:"className",
            required:true,
            type:"string"
        },
        {
            defaultValue:"false",
            name:"volatility",
            type:"boolean"
        },
        {
            defaultValue:"true",
            name:"durability",
            type:"boolean"
        },
        {
            defaultValue:"true",
            name:"recover",
            type:"boolean"
        },
        {
            name:"dataMap",
            showIf:"false",
            type:"Object"
        }
    ]
})
