isc.DataSource.create({
    Constructor:"SimpleType",
    ID:"SimpleType",
    addGlobalId:false,
    inheritsFrom:"DataSourceField",
    fields:[
        {
            name:"inheritsFrom",
            type:"string"
        },
        {
            name:"editorType",
            type:"string"
        }
    ]
})
