isc.DataSource.create({
    ID:"Validator",
    addGlobalId:"false",
    fields:{
        type:{
            type:"string"
        },
        name:{
            type:"string"
        },
        description:{
            type:"string"
        },
        stopIfFalse:{
            type:"boolean"
        },
        stopOnError:{
            type:"boolean"
        },
        validateOnChange:{
            type:"boolean"
        },
        clientOnly:{
            type:"boolean"
        },
        errorMessage:{
            type:"string"
        },
        max:{
            type:"float"
        },
        min:{
            type:"float"
        },
        exclusive:{
            type:"boolean"
        },
        mask:{
            type:"regexp"
        },
        transformTo:{
            type:"regexp"
        },
        precision:{
            type:"integer"
        },
        expression:{
            type:"string"
        },
        otherField:{
            type:"string"
        },
        list:{
            multiple:"true",
            type:"text"
        },
        valueMap:{
            type:"ValueMap"
        },
        substring:{
            type:"text"
        },
        operator:{
            type:"text"
        },
        count:{
            type:"integer"
        },
        applyWhen:{
            type:"AdvancedCriteria"
        },
        dependentFields:{
            multiple:"true",
            type:"string"
        },
        serverCondition:{
            type:"string"
        },
        serverObject:{
            type:"ServerObject"
        },
        fieldName:{
            type:"string"
        },
        triggerEvent:{
            type:"string"
        },
        message:{
            type:"string"
        },
        severity:{
            type:"string"
        },
        displayMode:{
            type:"string"
        },
        duration:{
            type:"integer"
        },
        formula:{
            type:"string"
        },
        formulaVars:{
            type:"ValueMap"
        }
    }
})
