isc.DataSource.create({
    Constructor:"WebService",
    ID:"WebService",
    addGlobalId:false,
    fields:[
        {
            name:"location",
            type:"url"
        },
        {
            name:"targetNamespace",
            type:"url"
        },
        {
            multiple:true,
            name:"schemaImports",
            type:"Object"
        },
        {
            multiple:true,
            name:"wsdlImports",
            type:"Object"
        },
        {
            multiple:true,
            name:"operations",
            type:"WebServiceOperation"
        },
        {
            multiple:true,
            name:"portTypes",
            type:"Object"
        },
        {
            multiple:true,
            name:"bindings",
            type:"Object"
        },
        {
            multiple:true,
            name:"messages",
            type:"WSDLMessage"
        },
        {
            name:"globalNamespaces",
            type:"Object"
        }
    ]
})
